### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by lewisakura** [Yevano/ytci-krist-miner#2]
Whenever I try and run your miner it always throws this:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/ytci/kristminer/KristMiner : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

Help?

**Comment by Yevano** [comment]
You'll need to have Java 8 installed if you want to run the binaries I provided. I'll leave this issue open until someone compiles for Java 7.

Of course, you could always just update your Java. :)

**Comment by lewisakura** [comment]
I don't want to update Java as I'll have to apply LegacyJavaFixer to my modded Minecraft.

**Comment by Yevano** [comment]
Check out [this post](http://www.computercraft.info/forums2/index.php?/topic/22201-krist-minable-currency-that-works-across-servers/page__view__findpost__p__221341) on the forum.

**Comment by lewisakura** [comment]
Cheers Yevano.
